version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - biomejs
  - brainfreeze
  - Chie
  - clsx
  - datatable
  - Dogaku
  - Dokudami
  - dori
  - excercise
  - fira
  - fontsource
  - Gakumon
  - Ganglioneuralgia
  - Genji
  - Goho
  - Heian
  - heikin
  - Inaba
  - kagami
  - kanko
  - kigo
  - kurumeii
  - mantine
  - Marineris
  - Mochi
  - Mori
  - Namib
  - Nanako
  - Natsume
  - nprogress
  - Ojisan
  - Okina
  - Ranmaru
  - remeda
  - Samegawa
  - Shichiri
  - Shochu
  - Shoping
  - Soseki
  - Souzai
  - Sphenopalatine
  - Susume
  - tabler
  - Tanaka’s
  - Tankiriman
  - tanstack
  - Toso
  - Valles
  - Wasan
  - Welwitschia
  - Yasogami
  - Yukiko's
ignoreWords: []
import: []
