import {
  IconArrowsSort,
  IconBookmark,
  IconBookmarkOff,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandTwitter,
  IconCalendar,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconHeart,
  IconHelp,
  IconHome,
  IconMaximize,
  IconMinimize,
  IconSearch,
  IconSettings,
  IconSortAscending,
  IconTrash,
  IconUsers
} from '@tabler/icons-react'

const Icons = {
  HomePage: IconHome,
  Answers: IconHelp,
  SocialLinks: IconUsers,
  ChevronRight: IconChevronRight,
  ChevronLeft: IconChevronLeft,
  ChevronUp: IconChevronUp,
  Heart: IconHeart,
  GitHub: IconBrandGithub,
  Twitter: IconBrandTwitter,
  Facebook: IconBrandFacebook,
  Calender: IconCalendar,
  Search: IconSearch,
  Clear: IconTrash,
  Sorted: IconSortAscending,
  Unsorted: IconArrowsSort,
  Marked: IconBookmark,
  Unmarked: IconBookmarkOff,
  Settings: IconSettings,
  Fullscreen: IconMaximize,
  ExitFullscreen: IconMinimize,
  Check: IconCheck,
}

export default Icons
